import tempfile
import unittest
from pathlib import Path

from ai.core.meta_calibrator import (
    build_training_row_from_validation,
    predict_meta_calibration,
    save_meta_model,
    train_meta_calibrator,
)
from config.settings import settings


class TestMetaCalibrator(unittest.TestCase):
    def test_build_training_row_from_validation_maps_expected_fields(self):
        row = {
            "project_key": "tistud",
            "issue_type": "bug",
            "selected_model": "heuristic_bucket_calibrated",
            "retrieval_route": "analogical_weak",
            "calibration_source": "focused_prior",
            "size_bucket": "M",
            "bucket_rank": 3,
            "heuristic_size_bucket": "M",
            "heuristic_bucket_rank": 3,
            "analogical_bucket_rank": 4,
            "base_hours": 8.0,
            "analogical_hours": 12.0,
            "heuristic_scope_hours": 7.0,
            "analogical_confidence": 0.62,
            "heuristic_scope_confidence": 0.74,
            "confidence": 0.6,
            "top1_score": 0.63,
            "top3_avg_score": 0.61,
            "useful_count": 0,
            "hours_spread": 1.5,
            "rag_context_sufficient": 1,
            "complexity_bucket_delta": 1,
            "agile_guard_bucket_delta": 0,
            "actual_hours": 9.0,
        }

        mapped = build_training_row_from_validation(row)

        self.assertEqual(mapped["project_key"], "tistud")
        self.assertEqual(mapped["issue_type"], "bug")
        self.assertEqual(mapped["heuristic_size_bucket"], "m")
        self.assertEqual(mapped["base_hours"], 8.0)
        self.assertEqual(mapped["actual_hours"], 9.0)
        self.assertGreater(mapped["analogical_log_hours"], mapped["heuristic_log_hours"])

    def test_predict_meta_calibration_uses_segment_prior_from_saved_model(self):
        training_rows = [
            {
                "project_key": "tistud",
                "issue_type": "bug",
                "retrieval_route": "analogical_weak",
                "heuristic_size_bucket": "m",
                "size_bucket": "m",
                "calibration_source": "focused_prior",
                "rule_selected_model": "heuristic_bucket_calibrated",
                "base_log_hours": 2.1,
                "analogical_log_hours": 2.2,
                "heuristic_log_hours": 2.0,
                "bucket_rank": 3,
                "heuristic_bucket_rank": 3,
                "analogical_bucket_rank": 4,
                "top1_score": 0.61,
                "top3_avg_score": 0.60,
                "useful_count": 0,
                "hours_spread": 1.4,
                "analogical_confidence": 0.6,
                "heuristic_confidence": 0.7,
                "base_confidence": 0.58,
                "bucket_gap": 1,
                "rag_context_sufficient": 1,
                "complexity_bucket_delta": 0,
                "agile_guard_bucket_delta": 0,
                "actual_hours": 7.0,
            },
            {
                "project_key": "tistud",
                "issue_type": "bug",
                "retrieval_route": "analogical_weak",
                "heuristic_size_bucket": "m",
                "size_bucket": "m",
                "calibration_source": "focused_prior",
                "rule_selected_model": "heuristic_bucket_calibrated",
                "base_log_hours": 2.0,
                "analogical_log_hours": 2.1,
                "heuristic_log_hours": 1.95,
                "bucket_rank": 3,
                "heuristic_bucket_rank": 3,
                "analogical_bucket_rank": 3,
                "top1_score": 0.59,
                "top3_avg_score": 0.58,
                "useful_count": 0,
                "hours_spread": 1.2,
                "analogical_confidence": 0.58,
                "heuristic_confidence": 0.7,
                "base_confidence": 0.56,
                "bucket_gap": 0,
                "rag_context_sufficient": 1,
                "complexity_bucket_delta": 0,
                "agile_guard_bucket_delta": 0,
                "actual_hours": 6.0,
            },
            {
                "project_key": "tistud",
                "issue_type": "bug",
                "retrieval_route": "analogical_weak",
                "heuristic_size_bucket": "m",
                "size_bucket": "m",
                "calibration_source": "focused_prior",
                "rule_selected_model": "heuristic_bucket_calibrated",
                "base_log_hours": 2.2,
                "analogical_log_hours": 2.25,
                "heuristic_log_hours": 2.05,
                "bucket_rank": 3,
                "heuristic_bucket_rank": 3,
                "analogical_bucket_rank": 4,
                "top1_score": 0.62,
                "top3_avg_score": 0.60,
                "useful_count": 0,
                "hours_spread": 1.3,
                "analogical_confidence": 0.61,
                "heuristic_confidence": 0.72,
                "base_confidence": 0.57,
                "bucket_gap": 1,
                "rag_context_sufficient": 1,
                "complexity_bucket_delta": 0,
                "agile_guard_bucket_delta": 0,
                "actual_hours": 8.0,
            },
            {
                "project_key": "tistud",
                "issue_type": "feature",
                "retrieval_route": "analogical_support",
                "heuristic_size_bucket": "l",
                "size_bucket": "l",
                "calibration_source": "focused_neighbors+all_neighbors",
                "rule_selected_model": "hybrid_calibrated",
                "base_log_hours": 2.8,
                "analogical_log_hours": 2.9,
                "heuristic_log_hours": 2.6,
                "bucket_rank": 4,
                "heuristic_bucket_rank": 4,
                "analogical_bucket_rank": 4,
                "top1_score": 0.8,
                "top3_avg_score": 0.76,
                "useful_count": 2,
                "hours_spread": 0.8,
                "analogical_confidence": 0.8,
                "heuristic_confidence": 0.72,
                "base_confidence": 0.68,
                "bucket_gap": 0,
                "rag_context_sufficient": 1,
                "complexity_bucket_delta": 0,
                "agile_guard_bucket_delta": 0,
                "actual_hours": 18.0,
            },
            {
                "project_key": "tistud",
                "issue_type": "feature",
                "retrieval_route": "analogical_support",
                "heuristic_size_bucket": "l",
                "size_bucket": "l",
                "calibration_source": "focused_neighbors+all_neighbors",
                "rule_selected_model": "hybrid_calibrated",
                "base_log_hours": 2.85,
                "analogical_log_hours": 2.95,
                "heuristic_log_hours": 2.7,
                "bucket_rank": 4,
                "heuristic_bucket_rank": 4,
                "analogical_bucket_rank": 4,
                "top1_score": 0.82,
                "top3_avg_score": 0.78,
                "useful_count": 2,
                "hours_spread": 0.7,
                "analogical_confidence": 0.82,
                "heuristic_confidence": 0.74,
                "base_confidence": 0.69,
                "bucket_gap": 0,
                "rag_context_sufficient": 1,
                "complexity_bucket_delta": 0,
                "agile_guard_bucket_delta": 0,
                "actual_hours": 20.0,
            },
            {
                "project_key": "tistud",
                "issue_type": "feature",
                "retrieval_route": "analogical_support",
                "heuristic_size_bucket": "l",
                "size_bucket": "l",
                "calibration_source": "focused_neighbors+all_neighbors",
                "rule_selected_model": "hybrid_calibrated",
                "base_log_hours": 2.75,
                "analogical_log_hours": 2.88,
                "heuristic_log_hours": 2.65,
                "bucket_rank": 4,
                "heuristic_bucket_rank": 4,
                "analogical_bucket_rank": 4,
                "top1_score": 0.79,
                "top3_avg_score": 0.75,
                "useful_count": 1,
                "hours_spread": 0.9,
                "analogical_confidence": 0.79,
                "heuristic_confidence": 0.71,
                "base_confidence": 0.67,
                "bucket_gap": 0,
                "rag_context_sufficient": 1,
                "complexity_bucket_delta": 0,
                "agile_guard_bucket_delta": 0,
                "actual_hours": 17.0,
            },
            {
                "project_key": "other",
                "issue_type": "task",
                "retrieval_route": "analogical_weak",
                "heuristic_size_bucket": "s",
                "size_bucket": "s",
                "calibration_source": "default_prior",
                "rule_selected_model": "heuristic_bucket_calibrated",
                "base_log_hours": 1.4,
                "analogical_log_hours": 1.5,
                "heuristic_log_hours": 1.35,
                "bucket_rank": 2,
                "heuristic_bucket_rank": 2,
                "analogical_bucket_rank": 2,
                "top1_score": 0.4,
                "top3_avg_score": 0.38,
                "useful_count": 0,
                "hours_spread": 1.8,
                "analogical_confidence": 0.3,
                "heuristic_confidence": 0.6,
                "base_confidence": 0.5,
                "bucket_gap": 0,
                "rag_context_sufficient": 0,
                "complexity_bucket_delta": 0,
                "agile_guard_bucket_delta": 0,
                "actual_hours": 3.0,
            },
            {
                "project_key": "other",
                "issue_type": "task",
                "retrieval_route": "analogical_weak",
                "heuristic_size_bucket": "s",
                "size_bucket": "s",
                "calibration_source": "default_prior",
                "rule_selected_model": "heuristic_bucket_calibrated",
                "base_log_hours": 1.45,
                "analogical_log_hours": 1.55,
                "heuristic_log_hours": 1.3,
                "bucket_rank": 2,
                "heuristic_bucket_rank": 2,
                "analogical_bucket_rank": 2,
                "top1_score": 0.42,
                "top3_avg_score": 0.40,
                "useful_count": 0,
                "hours_spread": 1.6,
                "analogical_confidence": 0.32,
                "heuristic_confidence": 0.58,
                "base_confidence": 0.49,
                "bucket_gap": 0,
                "rag_context_sufficient": 0,
                "complexity_bucket_delta": 0,
                "agile_guard_bucket_delta": 0,
                "actual_hours": 4.0,
            },
            {
                "project_key": "other",
                "issue_type": "task",
                "retrieval_route": "analogical_weak",
                "heuristic_size_bucket": "s",
                "size_bucket": "s",
                "calibration_source": "default_prior",
                "rule_selected_model": "heuristic_bucket_calibrated",
                "base_log_hours": 1.5,
                "analogical_log_hours": 1.6,
                "heuristic_log_hours": 1.4,
                "bucket_rank": 2,
                "heuristic_bucket_rank": 2,
                "analogical_bucket_rank": 2,
                "top1_score": 0.44,
                "top3_avg_score": 0.41,
                "useful_count": 0,
                "hours_spread": 1.5,
                "analogical_confidence": 0.31,
                "heuristic_confidence": 0.59,
                "base_confidence": 0.5,
                "bucket_gap": 0,
                "rag_context_sufficient": 0,
                "complexity_bucket_delta": 0,
                "agile_guard_bucket_delta": 0,
                "actual_hours": 5.0,
            },
            {
                "project_key": "other",
                "issue_type": "task",
                "retrieval_route": "analogical_weak",
                "heuristic_size_bucket": "m",
                "size_bucket": "m",
                "calibration_source": "focused_prior",
                "rule_selected_model": "heuristic_bucket_calibrated",
                "base_log_hours": 2.0,
                "analogical_log_hours": 2.0,
                "heuristic_log_hours": 2.0,
                "bucket_rank": 3,
                "heuristic_bucket_rank": 3,
                "analogical_bucket_rank": 3,
                "top1_score": 0.55,
                "top3_avg_score": 0.54,
                "useful_count": 0,
                "hours_spread": 1.2,
                "analogical_confidence": 0.45,
                "heuristic_confidence": 0.6,
                "base_confidence": 0.55,
                "bucket_gap": 0,
                "rag_context_sufficient": 1,
                "complexity_bucket_delta": 0,
                "agile_guard_bucket_delta": 0,
                "actual_hours": 9.0,
            },
            {
                "project_key": "other",
                "issue_type": "task",
                "retrieval_route": "analogical_weak",
                "heuristic_size_bucket": "m",
                "size_bucket": "m",
                "calibration_source": "focused_prior",
                "rule_selected_model": "heuristic_bucket_calibrated",
                "base_log_hours": 2.05,
                "analogical_log_hours": 2.08,
                "heuristic_log_hours": 2.0,
                "bucket_rank": 3,
                "heuristic_bucket_rank": 3,
                "analogical_bucket_rank": 3,
                "top1_score": 0.56,
                "top3_avg_score": 0.55,
                "useful_count": 0,
                "hours_spread": 1.1,
                "analogical_confidence": 0.46,
                "heuristic_confidence": 0.61,
                "base_confidence": 0.56,
                "bucket_gap": 0,
                "rag_context_sufficient": 1,
                "complexity_bucket_delta": 0,
                "agile_guard_bucket_delta": 0,
                "actual_hours": 10.0,
            },
            {
                "project_key": "other",
                "issue_type": "task",
                "retrieval_route": "analogical_weak",
                "heuristic_size_bucket": "m",
                "size_bucket": "m",
                "calibration_source": "focused_prior",
                "rule_selected_model": "heuristic_bucket_calibrated",
                "base_log_hours": 2.1,
                "analogical_log_hours": 2.12,
                "heuristic_log_hours": 2.02,
                "bucket_rank": 3,
                "heuristic_bucket_rank": 3,
                "analogical_bucket_rank": 3,
                "top1_score": 0.57,
                "top3_avg_score": 0.56,
                "useful_count": 0,
                "hours_spread": 1.0,
                "analogical_confidence": 0.47,
                "heuristic_confidence": 0.62,
                "base_confidence": 0.56,
                "bucket_gap": 0,
                "rag_context_sufficient": 1,
                "complexity_bucket_delta": 0,
                "agile_guard_bucket_delta": 0,
                "actual_hours": 11.0,
            },
        ]

        model = train_meta_calibrator(training_rows)

        previous_path = settings.META_CALIBRATOR_MODEL_PATH
        previous_enabled = settings.META_CALIBRATOR_ENABLED
        previous_min_count = settings.META_CALIBRATOR_MIN_SEGMENT_COUNT
        with tempfile.TemporaryDirectory() as tmpdir:
            output = Path(tmpdir) / "meta.json"
            save_meta_model(model, output)
            settings.META_CALIBRATOR_MODEL_PATH = str(output)
            settings.META_CALIBRATOR_ENABLED = True
            settings.META_CALIBRATOR_MIN_SEGMENT_COUNT = 3
            try:
                predicted = predict_meta_calibration(
                    {
                        "project_key": "tistud",
                        "issue_type": "bug",
                        "retrieval_route": "analogical_weak",
                        "heuristic_size_bucket": "m",
                        "size_bucket": "m",
                        "calibration_source": "focused_prior",
                        "rule_selected_model": "heuristic_bucket_calibrated",
                        "base_log_hours": 2.05,
                        "analogical_log_hours": 2.2,
                        "heuristic_log_hours": 2.0,
                        "bucket_rank": 3,
                        "heuristic_bucket_rank": 3,
                        "analogical_bucket_rank": 4,
                        "top1_score": 0.61,
                        "top3_avg_score": 0.60,
                        "useful_count": 0,
                        "hours_spread": 1.2,
                        "analogical_confidence": 0.6,
                        "heuristic_confidence": 0.72,
                        "base_confidence": 0.58,
                        "bucket_gap": 1,
                        "rag_context_sufficient": 1,
                        "complexity_bucket_delta": 0,
                        "agile_guard_bucket_delta": 0,
                    }
                )
            finally:
                settings.META_CALIBRATOR_MODEL_PATH = previous_path
                settings.META_CALIBRATOR_ENABLED = previous_enabled
                settings.META_CALIBRATOR_MIN_SEGMENT_COUNT = previous_min_count

        self.assertTrue(predicted["available"])
        self.assertEqual(predicted["prior_source"], "project_issue_route_bucket")
        self.assertGreaterEqual(predicted["prior_count"], 3)
        self.assertGreater(predicted["estimated_hours"], 6.0)
        self.assertLess(predicted["estimated_hours"], 9.0)

    def test_predict_meta_calibration_bounds_weak_route_correction(self):
        manual_model = {
            "model_type": "segmented_linear_residual",
            "model_version": "meta_calibrator_v2",
            "linear_model": {
                "bias": 1.0,
                "weights": {},
                "means": {},
                "scales": {},
                "features": [],
            },
            "category_adjustments": {},
            "segment_priors": {},
        }

        previous_path = settings.META_CALIBRATOR_MODEL_PATH
        previous_enabled = settings.META_CALIBRATOR_ENABLED
        with tempfile.TemporaryDirectory() as tmpdir:
            output = Path(tmpdir) / "meta.json"
            save_meta_model(manual_model, output)
            settings.META_CALIBRATOR_MODEL_PATH = str(output)
            settings.META_CALIBRATOR_ENABLED = True
            try:
                predicted = predict_meta_calibration(
                    {
                        "project_key": "tistud",
                        "issue_type": "bug",
                        "retrieval_route": "analogical_weak",
                        "heuristic_size_bucket": "m",
                        "size_bucket": "m",
                        "calibration_source": "focused_prior",
                        "rule_selected_model": "heuristic_bucket_calibrated",
                        "base_log_hours": 2.197224577,
                        "analogical_log_hours": 2.197224577,
                        "heuristic_log_hours": 2.197224577,
                        "bucket_rank": 3,
                        "heuristic_bucket_rank": 3,
                        "analogical_bucket_rank": 3,
                        "top1_score": 0.55,
                        "top3_avg_score": 0.54,
                        "useful_count": 0,
                        "hours_spread": 1.2,
                        "analogical_confidence": 0.35,
                        "heuristic_confidence": 0.62,
                        "base_confidence": 0.58,
                        "bucket_gap": 0,
                        "rag_context_sufficient": 1,
                        "complexity_bucket_delta": 0,
                        "agile_guard_bucket_delta": 0,
                    }
                )
            finally:
                settings.META_CALIBRATOR_MODEL_PATH = previous_path
                settings.META_CALIBRATOR_ENABLED = previous_enabled

        self.assertTrue(predicted["available"])
        self.assertEqual(predicted["estimated_hours"], 10.0)


if __name__ == "__main__":
    unittest.main()
